### PR TITLE
adding support for specifying contrast jar profile to download

### PR DESCRIPTION
**Pull request by wondersd**
Would like to use the contrast-maven-plugin with a spring boot maven project. For us this requires that we use the 'Spring-Boot' custom agent profile contrast.jar

### CODE REVIEW

**Comment by gmoore** [comment]
Thanks @wondersd 

@serge17 Can you pull this down and give it a test?

**Comment by serge17** [comment]
@gmoore It works fine.

**Comment by wondersd** [comment]
@gmoore @serge17 Thanks for looking at this! When can I expect this to get merged and a new release made?

**Comment by gmoore** [comment]
@wondersd Thanks for the nudge. I'll take care of it this coming week.

**Comment by gmoore** [comment]
@wondersd Pushed out 2.4 just now. Should be on Nexus in a few hours.

**Comment by wondersd** [comment]
@gmoore I see it in maven central, thanks!

**Pull request merged**
